name: Deploy Squarespace HTTrack Site to GitHub Pages

on:
  push:
    branches:
      - main   # deploy when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # Step 3: Upload site folder (new version)
      - name: Upload site folder
        uses: actions/upload-pages-artifact@v2
        with:
          path: r
