name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # deploy when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: rarelinkmap.squarespace.com  # folder containing index.html

      - name: Deploy
        uses: actions/deploy-pages@v1

