name: Deploy Squarespace HTTrack Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Configure GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # Step 3: Upload site folder (latest supported)
      - name: Upload site folder
        uses: actions/upload-pages-artifact@v2
        with:
          path: rarelinkmap.squarespace.com   # folder containing index.html

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
